### ISSUE TITLE
mods opcodes

### ISSUE THREAD

**Issue by Titan692** [TerableCoder/TerableOpcodes#3]
seems your opcodes and Lamba11's don't work together..i can't use the endless crafting mod if i use Lamb pet skill replacer mod..only 2 that clash eachother for some reason

**Comment by TerableCoder** [comment]
you're probably overwriting the protocol.350027.map file instead of copying the contents of it into your existing one

**Comment by Titan692** [comment]
this what i get.. https://gyazo.com/a7782b1d0938279334d94220b09e6656

**Comment by TerableCoder** [comment]
As said above, all you need to do is copy paste the below into your proxy's  \node_modules\tera-data\map\protocol.350027.map

C_PUT_WARE_ITEM = 44967
S_FISHING_CATCH = 27203
S_MEDAL_STORE_BASKET = 63265
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 37743
S_STORE_BASKET = 33177

C_EQUIP_ITEM = 35196
C_UNEQUIP_ITEM = 20429

C_START_FISHING_MINIGAME = 36919
C_END_FISHING_MINIGAME = 57240
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 30970
C_STORE_COMMIT = 46341
C_STORE_SELL_ADD_BASKET = 53110
C_CAST_FISHING_ROD = 43895

S_FISHING_BITE = 60499
S_CAST_FISHING_ROD = 50824
S_START_FISHING_MINIGAME = 60568

C_MEDAL_STORE_BUY_ADD_BASKET = 26269
C_MEDAL_STORE_COMMIT = 63629

S_DELETE_FRIEND = 31310
S_CANT_FLY_ANYMORE = 28763
S_FATIGABILITY_POINT = 39728
S_RP_SKILL_POLISHING_EXP_INFO = 49543

C_SELECT_CHANNEL = 61097
S_CANCEL_SELECT_CHANNEL = 54756
S_PREPARE_SELECT_CHANNEL = 54084
    
C_START_SERVANT_ACTIVE_SKILL = 29817

**Comment by Titan692** [comment]
yup what i did.. it working now.. i didn't think had to copy the notepad into it.. just that you had to drag and drop it in and it added all that in it.. i got it working as i just did that

**Comment by TerableCoder** [comment]
Nice!
